Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls_led/keras_model.h5'
OutputDir: hls_led
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: Dc4801d0
Version: 1.0.0
