// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_c2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_out_AWVALID,
        m_axi_gmem_out_AWREADY,
        m_axi_gmem_out_AWADDR,
        m_axi_gmem_out_AWID,
        m_axi_gmem_out_AWLEN,
        m_axi_gmem_out_AWSIZE,
        m_axi_gmem_out_AWBURST,
        m_axi_gmem_out_AWLOCK,
        m_axi_gmem_out_AWCACHE,
        m_axi_gmem_out_AWPROT,
        m_axi_gmem_out_AWQOS,
        m_axi_gmem_out_AWREGION,
        m_axi_gmem_out_AWUSER,
        m_axi_gmem_out_WVALID,
        m_axi_gmem_out_WREADY,
        m_axi_gmem_out_WDATA,
        m_axi_gmem_out_WSTRB,
        m_axi_gmem_out_WLAST,
        m_axi_gmem_out_WID,
        m_axi_gmem_out_WUSER,
        m_axi_gmem_out_ARVALID,
        m_axi_gmem_out_ARREADY,
        m_axi_gmem_out_ARADDR,
        m_axi_gmem_out_ARID,
        m_axi_gmem_out_ARLEN,
        m_axi_gmem_out_ARSIZE,
        m_axi_gmem_out_ARBURST,
        m_axi_gmem_out_ARLOCK,
        m_axi_gmem_out_ARCACHE,
        m_axi_gmem_out_ARPROT,
        m_axi_gmem_out_ARQOS,
        m_axi_gmem_out_ARREGION,
        m_axi_gmem_out_ARUSER,
        m_axi_gmem_out_RVALID,
        m_axi_gmem_out_RREADY,
        m_axi_gmem_out_RDATA,
        m_axi_gmem_out_RLAST,
        m_axi_gmem_out_RID,
        m_axi_gmem_out_RFIFONUM,
        m_axi_gmem_out_RUSER,
        m_axi_gmem_out_RRESP,
        m_axi_gmem_out_BVALID,
        m_axi_gmem_out_BREADY,
        m_axi_gmem_out_BRESP,
        m_axi_gmem_out_BID,
        m_axi_gmem_out_BUSER,
        input_r,
        output_r,
        grp_fu_830_p_din0,
        grp_fu_830_p_din1,
        grp_fu_830_p_opcode,
        grp_fu_830_p_dout0,
        grp_fu_830_p_ce,
        grp_fu_838_p_din0,
        grp_fu_838_p_din1,
        grp_fu_838_p_opcode,
        grp_fu_838_p_dout0,
        grp_fu_838_p_ce,
        grp_fu_834_p_din0,
        grp_fu_834_p_din1,
        grp_fu_834_p_dout0,
        grp_fu_834_p_ce
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_out_AWVALID;
input   m_axi_gmem_out_AWREADY;
output  [63:0] m_axi_gmem_out_AWADDR;
output  [0:0] m_axi_gmem_out_AWID;
output  [31:0] m_axi_gmem_out_AWLEN;
output  [2:0] m_axi_gmem_out_AWSIZE;
output  [1:0] m_axi_gmem_out_AWBURST;
output  [1:0] m_axi_gmem_out_AWLOCK;
output  [3:0] m_axi_gmem_out_AWCACHE;
output  [2:0] m_axi_gmem_out_AWPROT;
output  [3:0] m_axi_gmem_out_AWQOS;
output  [3:0] m_axi_gmem_out_AWREGION;
output  [0:0] m_axi_gmem_out_AWUSER;
output   m_axi_gmem_out_WVALID;
input   m_axi_gmem_out_WREADY;
output  [31:0] m_axi_gmem_out_WDATA;
output  [3:0] m_axi_gmem_out_WSTRB;
output   m_axi_gmem_out_WLAST;
output  [0:0] m_axi_gmem_out_WID;
output  [0:0] m_axi_gmem_out_WUSER;
output   m_axi_gmem_out_ARVALID;
input   m_axi_gmem_out_ARREADY;
output  [63:0] m_axi_gmem_out_ARADDR;
output  [0:0] m_axi_gmem_out_ARID;
output  [31:0] m_axi_gmem_out_ARLEN;
output  [2:0] m_axi_gmem_out_ARSIZE;
output  [1:0] m_axi_gmem_out_ARBURST;
output  [1:0] m_axi_gmem_out_ARLOCK;
output  [3:0] m_axi_gmem_out_ARCACHE;
output  [2:0] m_axi_gmem_out_ARPROT;
output  [3:0] m_axi_gmem_out_ARQOS;
output  [3:0] m_axi_gmem_out_ARREGION;
output  [0:0] m_axi_gmem_out_ARUSER;
input   m_axi_gmem_out_RVALID;
output   m_axi_gmem_out_RREADY;
input  [31:0] m_axi_gmem_out_RDATA;
input   m_axi_gmem_out_RLAST;
input  [0:0] m_axi_gmem_out_RID;
input  [8:0] m_axi_gmem_out_RFIFONUM;
input  [0:0] m_axi_gmem_out_RUSER;
input  [1:0] m_axi_gmem_out_RRESP;
input   m_axi_gmem_out_BVALID;
output   m_axi_gmem_out_BREADY;
input  [1:0] m_axi_gmem_out_BRESP;
input  [0:0] m_axi_gmem_out_BID;
input  [0:0] m_axi_gmem_out_BUSER;
input  [63:0] input_r;
input  [63:0] output_r;
output  [31:0] grp_fu_830_p_din0;
output  [31:0] grp_fu_830_p_din1;
output  [1:0] grp_fu_830_p_opcode;
input  [31:0] grp_fu_830_p_dout0;
output   grp_fu_830_p_ce;
output  [31:0] grp_fu_838_p_din0;
output  [31:0] grp_fu_838_p_din1;
output  [4:0] grp_fu_838_p_opcode;
input  [0:0] grp_fu_838_p_dout0;
output   grp_fu_838_p_ce;
output  [31:0] grp_fu_834_p_din0;
output  [31:0] grp_fu_834_p_din1;
input  [31:0] grp_fu_834_p_dout0;
output   grp_fu_834_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_out_AWVALID;
reg m_axi_gmem_out_WVALID;
reg m_axi_gmem_out_ARVALID;
reg m_axi_gmem_out_RREADY;
reg m_axi_gmem_out_BREADY;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] conv2_biases_address0;
reg    conv2_biases_ce0;
wire   [31:0] conv2_biases_q0;
reg    gmem_out_blk_n_AW;
wire    ap_CS_fsm_state5;
reg    gmem_out_blk_n_W;
wire    ap_CS_fsm_state12;
reg    gmem_out_blk_n_B;
wire    ap_CS_fsm_state17;
wire   [0:0] icmp_ln84_fu_262_p2;
reg   [0:0] icmp_ln84_reg_630;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln83_fu_244_p2;
wire   [3:0] select_ln84_fu_330_p3;
reg   [3:0] select_ln84_reg_635;
wire   [3:0] select_ln84_3_fu_374_p3;
reg   [3:0] select_ln84_3_reg_640;
wire   [12:0] add_ln100_1_fu_400_p2;
reg   [12:0] add_ln100_1_reg_645;
wire   [4:0] select_ln83_1_fu_455_p3;
reg   [4:0] select_ln83_1_reg_650;
wire    ap_CS_fsm_state3;
reg   [63:0] gmem_out_addr_reg_660;
reg   [31:0] conv2_biases_load_reg_666;
wire    ap_CS_fsm_state4;
reg   [31:0] sum_reg_674;
wire    ap_CS_fsm_state9;
wire   [31:0] select_ln100_fu_568_p3;
reg   [31:0] select_ln100_reg_680;
wire    ap_CS_fsm_state11;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_start;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_done;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_idle;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_ready;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWVALID;
wire   [63:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWADDR;
wire   [0:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWID;
wire   [31:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWLEN;
wire   [2:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWSIZE;
wire   [1:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWBURST;
wire   [1:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWLOCK;
wire   [3:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWCACHE;
wire   [2:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWPROT;
wire   [3:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWQOS;
wire   [3:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWREGION;
wire   [0:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWUSER;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WVALID;
wire   [31:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WDATA;
wire   [3:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WSTRB;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WLAST;
wire   [0:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WID;
wire   [0:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WUSER;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARVALID;
wire   [63:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARADDR;
wire   [0:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARID;
wire   [31:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARLEN;
wire   [2:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARSIZE;
wire   [1:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARBURST;
wire   [1:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARLOCK;
wire   [3:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARCACHE;
wire   [2:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARPROT;
wire   [3:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARQOS;
wire   [3:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARREGION;
wire   [0:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARUSER;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_RREADY;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_BREADY;
wire   [31:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_sum_6_out;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_sum_6_out_ap_vld;
wire   [31:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_din0;
wire   [31:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_din1;
wire   [1:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_opcode;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_ce;
wire   [31:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_685_p_din0;
wire   [31:0] grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_685_p_din1;
wire    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_685_p_ce;
reg    grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_start_reg;
wire   [63:0] zext_ln83_fu_463_p1;
wire  signed [63:0] sext_ln100_fu_508_p1;
reg   [3:0] j_fu_118;
wire   [3:0] add_ln85_fu_406_p2;
reg   [3:0] i_fu_122;
reg   [7:0] indvar_flatten32_fu_126;
wire   [7:0] select_ln84_4_fu_418_p3;
reg   [4:0] oc_fu_130;
reg   [10:0] indvar_flatten54_fu_134;
wire   [10:0] add_ln83_2_fu_250_p2;
reg   [31:0] grp_fu_196_p0;
reg   [31:0] grp_fu_196_p1;
wire   [12:0] shl_ln100_s_fu_276_p3;
wire   [10:0] shl_ln100_2_fu_236_p3;
wire   [0:0] icmp_ln85_fu_306_p2;
wire   [0:0] xor_ln83_fu_300_p2;
wire   [3:0] select_ln83_fu_268_p3;
wire   [0:0] and_ln83_fu_312_p2;
wire   [0:0] or_ln84_fu_324_p2;
wire   [3:0] add_ln84_fu_318_p2;
wire   [12:0] shl_ln100_1_mid1_fu_338_p3;
wire   [12:0] select_ln83_2_fu_284_p3;
wire   [10:0] shl_ln100_2_mid1_fu_354_p3;
wire   [10:0] select_ln83_3_fu_292_p3;
wire   [10:0] select_ln84_2_fu_362_p3;
wire   [9:0] shl_ln100_3_fu_382_p3;
wire   [12:0] select_ln84_1_fu_346_p3;
wire   [12:0] zext_ln100_fu_390_p1;
wire   [12:0] add_ln100_fu_394_p2;
wire   [12:0] zext_ln84_fu_370_p1;
wire   [7:0] add_ln84_1_fu_412_p2;
wire   [4:0] add_ln83_fu_449_p2;
wire   [3:0] trunc_ln83_fu_468_p1;
wire   [5:0] add_ln100_mid2_v_v_fu_472_p3;
wire   [63:0] zext_ln83_1_fu_480_p1;
wire   [63:0] zext_ln100_1_fu_489_p1;
wire   [63:0] add_ln83_1_fu_484_p2;
wire   [63:0] add_ln100_2_fu_492_p2;
wire   [61:0] trunc_ln_fu_498_p4;
wire   [31:0] bitcast_ln100_fu_527_p1;
wire   [7:0] tmp_s_fu_530_p4;
wire   [22:0] trunc_ln100_fu_540_p1;
wire   [0:0] icmp_ln100_1_fu_550_p2;
wire   [0:0] icmp_ln100_fu_544_p2;
wire   [0:0] or_ln100_fu_556_p2;
wire   [0:0] and_ln100_fu_562_p2;
reg    grp_fu_196_ce;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_fu_685_ce;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_start_reg = 1'b0;
end

top_c2_conv2_biases_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
conv2_biases_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv2_biases_address0),
    .ce0(conv2_biases_ce0),
    .q0(conv2_biases_q0)
);

top_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6 grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_start),
    .ap_done(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_done),
    .ap_idle(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_idle),
    .ap_ready(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_ready),
    .select_ln84_3(select_ln84_3_reg_640),
    .zext_ln83(select_ln83_1_reg_650),
    .select_ln84(select_ln84_reg_635),
    .input_r(input_r),
    .m_axi_gmem_out_AWVALID(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWVALID),
    .m_axi_gmem_out_AWREADY(1'b0),
    .m_axi_gmem_out_AWADDR(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWADDR),
    .m_axi_gmem_out_AWID(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWID),
    .m_axi_gmem_out_AWLEN(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWLEN),
    .m_axi_gmem_out_AWSIZE(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWSIZE),
    .m_axi_gmem_out_AWBURST(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWBURST),
    .m_axi_gmem_out_AWLOCK(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWLOCK),
    .m_axi_gmem_out_AWCACHE(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWCACHE),
    .m_axi_gmem_out_AWPROT(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWPROT),
    .m_axi_gmem_out_AWQOS(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWQOS),
    .m_axi_gmem_out_AWREGION(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWREGION),
    .m_axi_gmem_out_AWUSER(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_AWUSER),
    .m_axi_gmem_out_WVALID(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WVALID),
    .m_axi_gmem_out_WREADY(1'b0),
    .m_axi_gmem_out_WDATA(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WDATA),
    .m_axi_gmem_out_WSTRB(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WSTRB),
    .m_axi_gmem_out_WLAST(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WLAST),
    .m_axi_gmem_out_WID(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WID),
    .m_axi_gmem_out_WUSER(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_WUSER),
    .m_axi_gmem_out_ARVALID(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARVALID),
    .m_axi_gmem_out_ARREADY(m_axi_gmem_out_ARREADY),
    .m_axi_gmem_out_ARADDR(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARADDR),
    .m_axi_gmem_out_ARID(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARID),
    .m_axi_gmem_out_ARLEN(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARLEN),
    .m_axi_gmem_out_ARSIZE(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARSIZE),
    .m_axi_gmem_out_ARBURST(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARBURST),
    .m_axi_gmem_out_ARLOCK(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARLOCK),
    .m_axi_gmem_out_ARCACHE(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARCACHE),
    .m_axi_gmem_out_ARPROT(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARPROT),
    .m_axi_gmem_out_ARQOS(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARQOS),
    .m_axi_gmem_out_ARREGION(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARREGION),
    .m_axi_gmem_out_ARUSER(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARUSER),
    .m_axi_gmem_out_RVALID(m_axi_gmem_out_RVALID),
    .m_axi_gmem_out_RREADY(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_RREADY),
    .m_axi_gmem_out_RDATA(m_axi_gmem_out_RDATA),
    .m_axi_gmem_out_RLAST(m_axi_gmem_out_RLAST),
    .m_axi_gmem_out_RID(m_axi_gmem_out_RID),
    .m_axi_gmem_out_RFIFONUM(m_axi_gmem_out_RFIFONUM),
    .m_axi_gmem_out_RUSER(m_axi_gmem_out_RUSER),
    .m_axi_gmem_out_RRESP(m_axi_gmem_out_RRESP),
    .m_axi_gmem_out_BVALID(1'b0),
    .m_axi_gmem_out_BREADY(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_BREADY),
    .m_axi_gmem_out_BRESP(2'd0),
    .m_axi_gmem_out_BID(1'd0),
    .m_axi_gmem_out_BUSER(1'd0),
    .sum_6_out(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_sum_6_out),
    .sum_6_out_ap_vld(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_sum_6_out_ap_vld),
    .grp_fu_196_p_din0(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_din0),
    .grp_fu_196_p_din1(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_din1),
    .grp_fu_196_p_opcode(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_opcode),
    .grp_fu_196_p_dout0(grp_fu_830_p_dout0),
    .grp_fu_196_p_ce(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_ce),
    .grp_fu_685_p_din0(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_685_p_din0),
    .grp_fu_685_p_din1(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_685_p_din1),
    .grp_fu_685_p_dout0(grp_fu_834_p_dout0),
    .grp_fu_685_p_ce(grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_685_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_start_reg <= 1'b1;
        end else if ((grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_ready == 1'b1)) begin
            grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_122 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_244_p2 == 1'd0))) begin
        i_fu_122 <= select_ln84_3_fu_374_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten32_fu_126 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_244_p2 == 1'd0))) begin
        indvar_flatten32_fu_126 <= select_ln84_4_fu_418_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten54_fu_134 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_244_p2 == 1'd0))) begin
        indvar_flatten54_fu_134 <= add_ln83_2_fu_250_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_118 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_244_p2 == 1'd0))) begin
        j_fu_118 <= add_ln85_fu_406_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        oc_fu_130 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        oc_fu_130 <= select_ln83_1_fu_455_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_244_p2 == 1'd0))) begin
        add_ln100_1_reg_645[12 : 6] <= add_ln100_1_fu_400_p2[12 : 6];
        icmp_ln84_reg_630 <= icmp_ln84_fu_262_p2;
        select_ln84_3_reg_640 <= select_ln84_3_fu_374_p3;
        select_ln84_reg_635 <= select_ln84_fu_330_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv2_biases_load_reg_666 <= conv2_biases_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem_out_addr_reg_660 <= sext_ln100_fu_508_p1;
        select_ln83_1_reg_650 <= select_ln83_1_fu_455_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        select_ln100_reg_680 <= select_ln100_fu_568_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        sum_reg_674 <= grp_fu_830_p_dout0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_out_WREADY == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_out_BVALID == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_out_AWREADY == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_244_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_244_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        conv2_biases_ce0 = 1'b1;
    end else begin
        conv2_biases_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        gmem_out_blk_n_AW = m_axi_gmem_out_AWREADY;
    end else begin
        gmem_out_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        gmem_out_blk_n_B = m_axi_gmem_out_BVALID;
    end else begin
        gmem_out_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gmem_out_blk_n_W = m_axi_gmem_out_WREADY;
    end else begin
        gmem_out_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_196_ce = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state9) | ((m_axi_gmem_out_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        grp_fu_196_ce = 1'b1;
    end else begin
        grp_fu_196_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_196_p0 = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_196_p0 = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_sum_6_out;
    end else begin
        grp_fu_196_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_196_p1 = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_196_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_196_p1 = conv2_biases_load_reg_666;
    end else begin
        grp_fu_196_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_685_ce = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_685_p_ce;
    end else begin
        grp_fu_685_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_out_ARVALID = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARVALID;
    end else begin
        m_axi_gmem_out_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        m_axi_gmem_out_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_out_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        m_axi_gmem_out_BREADY = 1'b1;
    end else begin
        m_axi_gmem_out_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_out_RREADY = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_RREADY;
    end else begin
        m_axi_gmem_out_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        m_axi_gmem_out_WVALID = 1'b1;
    end else begin
        m_axi_gmem_out_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_244_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((m_axi_gmem_out_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((m_axi_gmem_out_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((m_axi_gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_1_fu_400_p2 = (add_ln100_fu_394_p2 + zext_ln84_fu_370_p1);

assign add_ln100_2_fu_492_p2 = (zext_ln100_1_fu_489_p1 + add_ln83_1_fu_484_p2);

assign add_ln100_fu_394_p2 = (select_ln84_1_fu_346_p3 + zext_ln100_fu_390_p1);

assign add_ln100_mid2_v_v_fu_472_p3 = {{trunc_ln83_fu_468_p1}, {2'd0}};

assign add_ln83_1_fu_484_p2 = (zext_ln83_1_fu_480_p1 + output_r);

assign add_ln83_2_fu_250_p2 = (indvar_flatten54_fu_134 + 11'd1);

assign add_ln83_fu_449_p2 = (oc_fu_130 + 5'd1);

assign add_ln84_1_fu_412_p2 = (indvar_flatten32_fu_126 + 8'd1);

assign add_ln84_fu_318_p2 = (select_ln83_fu_268_p3 + 4'd1);

assign add_ln85_fu_406_p2 = (select_ln84_fu_330_p3 + 4'd1);

assign and_ln100_fu_562_p2 = (or_ln100_fu_556_p2 & grp_fu_838_p_dout0);

assign and_ln83_fu_312_p2 = (xor_ln83_fu_300_p2 & icmp_ln85_fu_306_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln100_fu_527_p1 = sum_reg_674;

assign conv2_biases_address0 = zext_ln83_fu_463_p1;

assign grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_start = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_ap_start_reg;

assign grp_fu_830_p_ce = grp_fu_196_ce;

assign grp_fu_830_p_din0 = grp_fu_196_p0;

assign grp_fu_830_p_din1 = grp_fu_196_p1;

assign grp_fu_830_p_opcode = 2'd0;

assign grp_fu_834_p_ce = grp_fu_685_ce;

assign grp_fu_834_p_din0 = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_685_p_din0;

assign grp_fu_834_p_din1 = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_grp_fu_685_p_din1;

assign grp_fu_838_p_ce = 1'b1;

assign grp_fu_838_p_din0 = sum_reg_674;

assign grp_fu_838_p_din1 = 32'd0;

assign grp_fu_838_p_opcode = 5'd2;

assign icmp_ln100_1_fu_550_p2 = ((trunc_ln100_fu_540_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln100_fu_544_p2 = ((tmp_s_fu_530_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_244_p2 = ((indvar_flatten54_fu_134 == 11'd1600) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_262_p2 = ((indvar_flatten32_fu_126 == 8'd100) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_306_p2 = ((j_fu_118 == 4'd10) ? 1'b1 : 1'b0);

assign m_axi_gmem_out_ARADDR = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARADDR;

assign m_axi_gmem_out_ARBURST = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARBURST;

assign m_axi_gmem_out_ARCACHE = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARCACHE;

assign m_axi_gmem_out_ARID = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARID;

assign m_axi_gmem_out_ARLEN = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARLEN;

assign m_axi_gmem_out_ARLOCK = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARLOCK;

assign m_axi_gmem_out_ARPROT = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARPROT;

assign m_axi_gmem_out_ARQOS = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARQOS;

assign m_axi_gmem_out_ARREGION = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARREGION;

assign m_axi_gmem_out_ARSIZE = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARSIZE;

assign m_axi_gmem_out_ARUSER = grp_c2_Pipeline_VITIS_LOOP_89_4_VITIS_LOOP_90_5_VITIS_LOOP_91_6_fu_183_m_axi_gmem_out_ARUSER;

assign m_axi_gmem_out_AWADDR = gmem_out_addr_reg_660;

assign m_axi_gmem_out_AWBURST = 2'd0;

assign m_axi_gmem_out_AWCACHE = 4'd0;

assign m_axi_gmem_out_AWID = 1'd0;

assign m_axi_gmem_out_AWLEN = 32'd1;

assign m_axi_gmem_out_AWLOCK = 2'd0;

assign m_axi_gmem_out_AWPROT = 3'd0;

assign m_axi_gmem_out_AWQOS = 4'd0;

assign m_axi_gmem_out_AWREGION = 4'd0;

assign m_axi_gmem_out_AWSIZE = 3'd0;

assign m_axi_gmem_out_AWUSER = 1'd0;

assign m_axi_gmem_out_WDATA = select_ln100_reg_680;

assign m_axi_gmem_out_WID = 1'd0;

assign m_axi_gmem_out_WLAST = 1'b0;

assign m_axi_gmem_out_WSTRB = 4'd15;

assign m_axi_gmem_out_WUSER = 1'd0;

assign or_ln100_fu_556_p2 = (icmp_ln100_fu_544_p2 | icmp_ln100_1_fu_550_p2);

assign or_ln84_fu_324_p2 = (icmp_ln84_fu_262_p2 | and_ln83_fu_312_p2);

assign select_ln100_fu_568_p3 = ((and_ln100_fu_562_p2[0:0] == 1'b1) ? bitcast_ln100_fu_527_p1 : 32'd0);

assign select_ln83_1_fu_455_p3 = ((icmp_ln84_reg_630[0:0] == 1'b1) ? add_ln83_fu_449_p2 : oc_fu_130);

assign select_ln83_2_fu_284_p3 = ((icmp_ln84_fu_262_p2[0:0] == 1'b1) ? 13'd0 : shl_ln100_s_fu_276_p3);

assign select_ln83_3_fu_292_p3 = ((icmp_ln84_fu_262_p2[0:0] == 1'b1) ? 11'd0 : shl_ln100_2_fu_236_p3);

assign select_ln83_fu_268_p3 = ((icmp_ln84_fu_262_p2[0:0] == 1'b1) ? 4'd0 : i_fu_122);

assign select_ln84_1_fu_346_p3 = ((and_ln83_fu_312_p2[0:0] == 1'b1) ? shl_ln100_1_mid1_fu_338_p3 : select_ln83_2_fu_284_p3);

assign select_ln84_2_fu_362_p3 = ((and_ln83_fu_312_p2[0:0] == 1'b1) ? shl_ln100_2_mid1_fu_354_p3 : select_ln83_3_fu_292_p3);

assign select_ln84_3_fu_374_p3 = ((and_ln83_fu_312_p2[0:0] == 1'b1) ? add_ln84_fu_318_p2 : select_ln83_fu_268_p3);

assign select_ln84_4_fu_418_p3 = ((icmp_ln84_fu_262_p2[0:0] == 1'b1) ? 8'd1 : add_ln84_1_fu_412_p2);

assign select_ln84_fu_330_p3 = ((or_ln84_fu_324_p2[0:0] == 1'b1) ? 4'd0 : j_fu_118);

assign sext_ln100_fu_508_p1 = $signed(trunc_ln_fu_498_p4);

assign shl_ln100_1_mid1_fu_338_p3 = {{add_ln84_fu_318_p2}, {9'd0}};

assign shl_ln100_2_fu_236_p3 = {{i_fu_122}, {7'd0}};

assign shl_ln100_2_mid1_fu_354_p3 = {{add_ln84_fu_318_p2}, {7'd0}};

assign shl_ln100_3_fu_382_p3 = {{select_ln84_fu_330_p3}, {6'd0}};

assign shl_ln100_s_fu_276_p3 = {{i_fu_122}, {9'd0}};

assign tmp_s_fu_530_p4 = {{bitcast_ln100_fu_527_p1[30:23]}};

assign trunc_ln100_fu_540_p1 = bitcast_ln100_fu_527_p1[22:0];

assign trunc_ln83_fu_468_p1 = select_ln83_1_fu_455_p3[3:0];

assign trunc_ln_fu_498_p4 = {{add_ln100_2_fu_492_p2[63:2]}};

assign xor_ln83_fu_300_p2 = (icmp_ln84_fu_262_p2 ^ 1'd1);

assign zext_ln100_1_fu_489_p1 = add_ln100_1_reg_645;

assign zext_ln100_fu_390_p1 = shl_ln100_3_fu_382_p3;

assign zext_ln83_1_fu_480_p1 = add_ln100_mid2_v_v_fu_472_p3;

assign zext_ln83_fu_463_p1 = select_ln83_1_fu_455_p3;

assign zext_ln84_fu_370_p1 = select_ln84_2_fu_362_p3;

always @ (posedge ap_clk) begin
    add_ln100_1_reg_645[5:0] <= 6'b000000;
end

endmodule //top_c2
