// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_f1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_out_0_AWVALID,
        m_axi_gmem_out_0_AWREADY,
        m_axi_gmem_out_0_AWADDR,
        m_axi_gmem_out_0_AWID,
        m_axi_gmem_out_0_AWLEN,
        m_axi_gmem_out_0_AWSIZE,
        m_axi_gmem_out_0_AWBURST,
        m_axi_gmem_out_0_AWLOCK,
        m_axi_gmem_out_0_AWCACHE,
        m_axi_gmem_out_0_AWPROT,
        m_axi_gmem_out_0_AWQOS,
        m_axi_gmem_out_0_AWREGION,
        m_axi_gmem_out_0_AWUSER,
        m_axi_gmem_out_0_WVALID,
        m_axi_gmem_out_0_WREADY,
        m_axi_gmem_out_0_WDATA,
        m_axi_gmem_out_0_WSTRB,
        m_axi_gmem_out_0_WLAST,
        m_axi_gmem_out_0_WID,
        m_axi_gmem_out_0_WUSER,
        m_axi_gmem_out_0_ARVALID,
        m_axi_gmem_out_0_ARREADY,
        m_axi_gmem_out_0_ARADDR,
        m_axi_gmem_out_0_ARID,
        m_axi_gmem_out_0_ARLEN,
        m_axi_gmem_out_0_ARSIZE,
        m_axi_gmem_out_0_ARBURST,
        m_axi_gmem_out_0_ARLOCK,
        m_axi_gmem_out_0_ARCACHE,
        m_axi_gmem_out_0_ARPROT,
        m_axi_gmem_out_0_ARQOS,
        m_axi_gmem_out_0_ARREGION,
        m_axi_gmem_out_0_ARUSER,
        m_axi_gmem_out_0_RVALID,
        m_axi_gmem_out_0_RREADY,
        m_axi_gmem_out_0_RDATA,
        m_axi_gmem_out_0_RLAST,
        m_axi_gmem_out_0_RID,
        m_axi_gmem_out_0_RFIFONUM,
        m_axi_gmem_out_0_RUSER,
        m_axi_gmem_out_0_RRESP,
        m_axi_gmem_out_0_BVALID,
        m_axi_gmem_out_0_BREADY,
        m_axi_gmem_out_0_BRESP,
        m_axi_gmem_out_0_BID,
        m_axi_gmem_out_0_BUSER,
        input_r,
        output_r
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_out_0_AWVALID;
input   m_axi_gmem_out_0_AWREADY;
output  [63:0] m_axi_gmem_out_0_AWADDR;
output  [0:0] m_axi_gmem_out_0_AWID;
output  [31:0] m_axi_gmem_out_0_AWLEN;
output  [2:0] m_axi_gmem_out_0_AWSIZE;
output  [1:0] m_axi_gmem_out_0_AWBURST;
output  [1:0] m_axi_gmem_out_0_AWLOCK;
output  [3:0] m_axi_gmem_out_0_AWCACHE;
output  [2:0] m_axi_gmem_out_0_AWPROT;
output  [3:0] m_axi_gmem_out_0_AWQOS;
output  [3:0] m_axi_gmem_out_0_AWREGION;
output  [0:0] m_axi_gmem_out_0_AWUSER;
output   m_axi_gmem_out_0_WVALID;
input   m_axi_gmem_out_0_WREADY;
output  [31:0] m_axi_gmem_out_0_WDATA;
output  [3:0] m_axi_gmem_out_0_WSTRB;
output   m_axi_gmem_out_0_WLAST;
output  [0:0] m_axi_gmem_out_0_WID;
output  [0:0] m_axi_gmem_out_0_WUSER;
output   m_axi_gmem_out_0_ARVALID;
input   m_axi_gmem_out_0_ARREADY;
output  [63:0] m_axi_gmem_out_0_ARADDR;
output  [0:0] m_axi_gmem_out_0_ARID;
output  [31:0] m_axi_gmem_out_0_ARLEN;
output  [2:0] m_axi_gmem_out_0_ARSIZE;
output  [1:0] m_axi_gmem_out_0_ARBURST;
output  [1:0] m_axi_gmem_out_0_ARLOCK;
output  [3:0] m_axi_gmem_out_0_ARCACHE;
output  [2:0] m_axi_gmem_out_0_ARPROT;
output  [3:0] m_axi_gmem_out_0_ARQOS;
output  [3:0] m_axi_gmem_out_0_ARREGION;
output  [0:0] m_axi_gmem_out_0_ARUSER;
input   m_axi_gmem_out_0_RVALID;
output   m_axi_gmem_out_0_RREADY;
input  [31:0] m_axi_gmem_out_0_RDATA;
input   m_axi_gmem_out_0_RLAST;
input  [0:0] m_axi_gmem_out_0_RID;
input  [8:0] m_axi_gmem_out_0_RFIFONUM;
input  [0:0] m_axi_gmem_out_0_RUSER;
input  [1:0] m_axi_gmem_out_0_RRESP;
input   m_axi_gmem_out_0_BVALID;
output   m_axi_gmem_out_0_BREADY;
input  [1:0] m_axi_gmem_out_0_BRESP;
input  [0:0] m_axi_gmem_out_0_BID;
input  [0:0] m_axi_gmem_out_0_BUSER;
input  [63:0] input_r;
input  [63:0] output_r;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_out_0_AWVALID;
reg[63:0] m_axi_gmem_out_0_AWADDR;
reg[0:0] m_axi_gmem_out_0_AWID;
reg[31:0] m_axi_gmem_out_0_AWLEN;
reg[2:0] m_axi_gmem_out_0_AWSIZE;
reg[1:0] m_axi_gmem_out_0_AWBURST;
reg[1:0] m_axi_gmem_out_0_AWLOCK;
reg[3:0] m_axi_gmem_out_0_AWCACHE;
reg[2:0] m_axi_gmem_out_0_AWPROT;
reg[3:0] m_axi_gmem_out_0_AWQOS;
reg[3:0] m_axi_gmem_out_0_AWREGION;
reg[0:0] m_axi_gmem_out_0_AWUSER;
reg m_axi_gmem_out_0_WVALID;
reg m_axi_gmem_out_0_ARVALID;
reg[63:0] m_axi_gmem_out_0_ARADDR;
reg[0:0] m_axi_gmem_out_0_ARID;
reg[31:0] m_axi_gmem_out_0_ARLEN;
reg[2:0] m_axi_gmem_out_0_ARSIZE;
reg[1:0] m_axi_gmem_out_0_ARBURST;
reg[1:0] m_axi_gmem_out_0_ARLOCK;
reg[3:0] m_axi_gmem_out_0_ARCACHE;
reg[2:0] m_axi_gmem_out_0_ARPROT;
reg[3:0] m_axi_gmem_out_0_ARQOS;
reg[3:0] m_axi_gmem_out_0_ARREGION;
reg[0:0] m_axi_gmem_out_0_ARUSER;
reg m_axi_gmem_out_0_RREADY;
reg m_axi_gmem_out_0_BREADY;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_out_blk_n_AR;
reg    gmem_out_blk_n_AW;
wire    ap_CS_fsm_state8;
reg    gmem_out_blk_n_B;
wire    ap_CS_fsm_state15;
wire  signed [61:0] trunc_ln_fu_81_p4;
reg   [61:0] trunc_ln_reg_123;
wire  signed [61:0] trunc_ln138_1_fu_102_p4;
reg   [61:0] trunc_ln138_1_reg_133;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_start;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_done;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_idle;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_ready;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWVALID;
wire   [63:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWADDR;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWID;
wire   [31:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWLEN;
wire   [2:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWSIZE;
wire   [1:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWBURST;
wire   [1:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWLOCK;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWCACHE;
wire   [2:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWPROT;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWQOS;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWREGION;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWUSER;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WVALID;
wire   [31:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WDATA;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WSTRB;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WLAST;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WID;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WUSER;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARVALID;
wire   [63:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARADDR;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARID;
wire   [31:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARLEN;
wire   [2:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARSIZE;
wire   [1:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARBURST;
wire   [1:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARLOCK;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARCACHE;
wire   [2:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARPROT;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARQOS;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARREGION;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARUSER;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_RREADY;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_BREADY;
reg    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire  signed [63:0] sext_ln138_fu_91_p1;
wire  signed [63:0] sext_ln138_1_fu_112_p1;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_start_reg = 1'b0;
end

top_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3 grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_start),
    .ap_done(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_done),
    .ap_idle(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_idle),
    .ap_ready(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_ready),
    .m_axi_gmem_out_0_AWVALID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWVALID),
    .m_axi_gmem_out_0_AWREADY(m_axi_gmem_out_0_AWREADY),
    .m_axi_gmem_out_0_AWADDR(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWADDR),
    .m_axi_gmem_out_0_AWID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWID),
    .m_axi_gmem_out_0_AWLEN(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWLEN),
    .m_axi_gmem_out_0_AWSIZE(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWSIZE),
    .m_axi_gmem_out_0_AWBURST(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWBURST),
    .m_axi_gmem_out_0_AWLOCK(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWLOCK),
    .m_axi_gmem_out_0_AWCACHE(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWCACHE),
    .m_axi_gmem_out_0_AWPROT(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWPROT),
    .m_axi_gmem_out_0_AWQOS(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWQOS),
    .m_axi_gmem_out_0_AWREGION(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWREGION),
    .m_axi_gmem_out_0_AWUSER(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWUSER),
    .m_axi_gmem_out_0_WVALID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WVALID),
    .m_axi_gmem_out_0_WREADY(m_axi_gmem_out_0_WREADY),
    .m_axi_gmem_out_0_WDATA(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WDATA),
    .m_axi_gmem_out_0_WSTRB(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WSTRB),
    .m_axi_gmem_out_0_WLAST(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WLAST),
    .m_axi_gmem_out_0_WID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WID),
    .m_axi_gmem_out_0_WUSER(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WUSER),
    .m_axi_gmem_out_0_ARVALID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARVALID),
    .m_axi_gmem_out_0_ARREADY(m_axi_gmem_out_0_ARREADY),
    .m_axi_gmem_out_0_ARADDR(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARADDR),
    .m_axi_gmem_out_0_ARID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARID),
    .m_axi_gmem_out_0_ARLEN(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARLEN),
    .m_axi_gmem_out_0_ARSIZE(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARSIZE),
    .m_axi_gmem_out_0_ARBURST(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARBURST),
    .m_axi_gmem_out_0_ARLOCK(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARLOCK),
    .m_axi_gmem_out_0_ARCACHE(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARCACHE),
    .m_axi_gmem_out_0_ARPROT(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARPROT),
    .m_axi_gmem_out_0_ARQOS(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARQOS),
    .m_axi_gmem_out_0_ARREGION(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARREGION),
    .m_axi_gmem_out_0_ARUSER(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARUSER),
    .m_axi_gmem_out_0_RVALID(m_axi_gmem_out_0_RVALID),
    .m_axi_gmem_out_0_RREADY(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_RREADY),
    .m_axi_gmem_out_0_RDATA(m_axi_gmem_out_0_RDATA),
    .m_axi_gmem_out_0_RLAST(m_axi_gmem_out_0_RLAST),
    .m_axi_gmem_out_0_RID(m_axi_gmem_out_0_RID),
    .m_axi_gmem_out_0_RFIFONUM(m_axi_gmem_out_0_RFIFONUM),
    .m_axi_gmem_out_0_RUSER(m_axi_gmem_out_0_RUSER),
    .m_axi_gmem_out_0_RRESP(m_axi_gmem_out_0_RRESP),
    .m_axi_gmem_out_0_BVALID(m_axi_gmem_out_0_BVALID),
    .m_axi_gmem_out_0_BREADY(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_BREADY),
    .m_axi_gmem_out_0_BRESP(m_axi_gmem_out_0_BRESP),
    .m_axi_gmem_out_0_BID(m_axi_gmem_out_0_BID),
    .m_axi_gmem_out_0_BUSER(m_axi_gmem_out_0_BUSER),
    .sext_ln138(trunc_ln_reg_123),
    .sext_ln138_1(trunc_ln138_1_reg_133)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_start_reg <= 1'b1;
        end else if ((grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_ready == 1'b1)) begin
            grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        trunc_ln138_1_reg_133 <= {{output_r[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln_reg_123 <= {{input_r[63:2]}};
    end
end

always @ (*) begin
    if ((grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_out_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_0_ARREADY == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_out_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((m_axi_gmem_out_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        gmem_out_blk_n_AR = m_axi_gmem_out_0_ARREADY;
    end else begin
        gmem_out_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gmem_out_blk_n_AW = m_axi_gmem_out_0_AWREADY;
    end else begin
        gmem_out_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gmem_out_blk_n_B = m_axi_gmem_out_0_BVALID;
    end else begin
        gmem_out_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_out_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_out_0_ARADDR = sext_ln138_fu_91_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARADDR = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARADDR;
    end else begin
        m_axi_gmem_out_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARBURST = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARBURST;
    end else begin
        m_axi_gmem_out_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARCACHE = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARCACHE;
    end else begin
        m_axi_gmem_out_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARID;
    end else begin
        m_axi_gmem_out_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_out_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_out_0_ARLEN = 64'd400;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARLEN = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARLEN;
    end else begin
        m_axi_gmem_out_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARLOCK = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARLOCK;
    end else begin
        m_axi_gmem_out_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARPROT = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARPROT;
    end else begin
        m_axi_gmem_out_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARQOS = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARQOS;
    end else begin
        m_axi_gmem_out_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARREGION = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARREGION;
    end else begin
        m_axi_gmem_out_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARSIZE = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARSIZE;
    end else begin
        m_axi_gmem_out_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARUSER = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARUSER;
    end else begin
        m_axi_gmem_out_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_out_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_out_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_ARVALID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_ARVALID;
    end else begin
        m_axi_gmem_out_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem_out_0_AWADDR = sext_ln138_1_fu_112_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWADDR = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWADDR;
    end else begin
        m_axi_gmem_out_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWBURST = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWBURST;
    end else begin
        m_axi_gmem_out_0_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWCACHE = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWCACHE;
    end else begin
        m_axi_gmem_out_0_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWID;
    end else begin
        m_axi_gmem_out_0_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem_out_0_AWLEN = 64'd400;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWLEN = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWLEN;
    end else begin
        m_axi_gmem_out_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWLOCK = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWLOCK;
    end else begin
        m_axi_gmem_out_0_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWPROT = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWPROT;
    end else begin
        m_axi_gmem_out_0_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWQOS = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWQOS;
    end else begin
        m_axi_gmem_out_0_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWREGION = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWREGION;
    end else begin
        m_axi_gmem_out_0_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWSIZE = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWSIZE;
    end else begin
        m_axi_gmem_out_0_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWUSER = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWUSER;
    end else begin
        m_axi_gmem_out_0_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem_out_0_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_AWVALID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_AWVALID;
    end else begin
        m_axi_gmem_out_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        m_axi_gmem_out_0_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_BREADY = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_BREADY;
    end else begin
        m_axi_gmem_out_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_RREADY = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_RREADY;
    end else begin
        m_axi_gmem_out_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_0_WVALID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WVALID;
    end else begin
        m_axi_gmem_out_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_gmem_out_0_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((m_axi_gmem_out_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((m_axi_gmem_out_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_start = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_ap_start_reg;

assign m_axi_gmem_out_0_WDATA = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WDATA;

assign m_axi_gmem_out_0_WID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WID;

assign m_axi_gmem_out_0_WLAST = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WLAST;

assign m_axi_gmem_out_0_WSTRB = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WSTRB;

assign m_axi_gmem_out_0_WUSER = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_73_m_axi_gmem_out_0_WUSER;

assign sext_ln138_1_fu_112_p1 = trunc_ln138_1_fu_102_p4;

assign sext_ln138_fu_91_p1 = trunc_ln_fu_81_p4;

assign trunc_ln138_1_fu_102_p4 = {{output_r[63:2]}};

assign trunc_ln_fu_81_p4 = {{input_r[63:2]}};

endmodule //top_f1
