// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_f1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_out_AWVALID,
        m_axi_gmem_out_AWREADY,
        m_axi_gmem_out_AWADDR,
        m_axi_gmem_out_AWID,
        m_axi_gmem_out_AWLEN,
        m_axi_gmem_out_AWSIZE,
        m_axi_gmem_out_AWBURST,
        m_axi_gmem_out_AWLOCK,
        m_axi_gmem_out_AWCACHE,
        m_axi_gmem_out_AWPROT,
        m_axi_gmem_out_AWQOS,
        m_axi_gmem_out_AWREGION,
        m_axi_gmem_out_AWUSER,
        m_axi_gmem_out_WVALID,
        m_axi_gmem_out_WREADY,
        m_axi_gmem_out_WDATA,
        m_axi_gmem_out_WSTRB,
        m_axi_gmem_out_WLAST,
        m_axi_gmem_out_WID,
        m_axi_gmem_out_WUSER,
        m_axi_gmem_out_ARVALID,
        m_axi_gmem_out_ARREADY,
        m_axi_gmem_out_ARADDR,
        m_axi_gmem_out_ARID,
        m_axi_gmem_out_ARLEN,
        m_axi_gmem_out_ARSIZE,
        m_axi_gmem_out_ARBURST,
        m_axi_gmem_out_ARLOCK,
        m_axi_gmem_out_ARCACHE,
        m_axi_gmem_out_ARPROT,
        m_axi_gmem_out_ARQOS,
        m_axi_gmem_out_ARREGION,
        m_axi_gmem_out_ARUSER,
        m_axi_gmem_out_RVALID,
        m_axi_gmem_out_RREADY,
        m_axi_gmem_out_RDATA,
        m_axi_gmem_out_RLAST,
        m_axi_gmem_out_RID,
        m_axi_gmem_out_RFIFONUM,
        m_axi_gmem_out_RUSER,
        m_axi_gmem_out_RRESP,
        m_axi_gmem_out_BVALID,
        m_axi_gmem_out_BREADY,
        m_axi_gmem_out_BRESP,
        m_axi_gmem_out_BID,
        m_axi_gmem_out_BUSER,
        input_r,
        output_r
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_out_AWVALID;
input   m_axi_gmem_out_AWREADY;
output  [63:0] m_axi_gmem_out_AWADDR;
output  [0:0] m_axi_gmem_out_AWID;
output  [31:0] m_axi_gmem_out_AWLEN;
output  [2:0] m_axi_gmem_out_AWSIZE;
output  [1:0] m_axi_gmem_out_AWBURST;
output  [1:0] m_axi_gmem_out_AWLOCK;
output  [3:0] m_axi_gmem_out_AWCACHE;
output  [2:0] m_axi_gmem_out_AWPROT;
output  [3:0] m_axi_gmem_out_AWQOS;
output  [3:0] m_axi_gmem_out_AWREGION;
output  [0:0] m_axi_gmem_out_AWUSER;
output   m_axi_gmem_out_WVALID;
input   m_axi_gmem_out_WREADY;
output  [31:0] m_axi_gmem_out_WDATA;
output  [3:0] m_axi_gmem_out_WSTRB;
output   m_axi_gmem_out_WLAST;
output  [0:0] m_axi_gmem_out_WID;
output  [0:0] m_axi_gmem_out_WUSER;
output   m_axi_gmem_out_ARVALID;
input   m_axi_gmem_out_ARREADY;
output  [63:0] m_axi_gmem_out_ARADDR;
output  [0:0] m_axi_gmem_out_ARID;
output  [31:0] m_axi_gmem_out_ARLEN;
output  [2:0] m_axi_gmem_out_ARSIZE;
output  [1:0] m_axi_gmem_out_ARBURST;
output  [1:0] m_axi_gmem_out_ARLOCK;
output  [3:0] m_axi_gmem_out_ARCACHE;
output  [2:0] m_axi_gmem_out_ARPROT;
output  [3:0] m_axi_gmem_out_ARQOS;
output  [3:0] m_axi_gmem_out_ARREGION;
output  [0:0] m_axi_gmem_out_ARUSER;
input   m_axi_gmem_out_RVALID;
output   m_axi_gmem_out_RREADY;
input  [31:0] m_axi_gmem_out_RDATA;
input   m_axi_gmem_out_RLAST;
input  [0:0] m_axi_gmem_out_RID;
input  [8:0] m_axi_gmem_out_RFIFONUM;
input  [0:0] m_axi_gmem_out_RUSER;
input  [1:0] m_axi_gmem_out_RRESP;
input   m_axi_gmem_out_BVALID;
output   m_axi_gmem_out_BREADY;
input  [1:0] m_axi_gmem_out_BRESP;
input  [0:0] m_axi_gmem_out_BID;
input  [0:0] m_axi_gmem_out_BUSER;
input  [63:0] input_r;
input  [63:0] output_r;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_out_AWVALID;
reg[63:0] m_axi_gmem_out_AWADDR;
reg[0:0] m_axi_gmem_out_AWID;
reg[31:0] m_axi_gmem_out_AWLEN;
reg[2:0] m_axi_gmem_out_AWSIZE;
reg[1:0] m_axi_gmem_out_AWBURST;
reg[1:0] m_axi_gmem_out_AWLOCK;
reg[3:0] m_axi_gmem_out_AWCACHE;
reg[2:0] m_axi_gmem_out_AWPROT;
reg[3:0] m_axi_gmem_out_AWQOS;
reg[3:0] m_axi_gmem_out_AWREGION;
reg[0:0] m_axi_gmem_out_AWUSER;
reg m_axi_gmem_out_WVALID;
reg m_axi_gmem_out_ARVALID;
reg[63:0] m_axi_gmem_out_ARADDR;
reg[0:0] m_axi_gmem_out_ARID;
reg[31:0] m_axi_gmem_out_ARLEN;
reg[2:0] m_axi_gmem_out_ARSIZE;
reg[1:0] m_axi_gmem_out_ARBURST;
reg[1:0] m_axi_gmem_out_ARLOCK;
reg[3:0] m_axi_gmem_out_ARCACHE;
reg[2:0] m_axi_gmem_out_ARPROT;
reg[3:0] m_axi_gmem_out_ARQOS;
reg[3:0] m_axi_gmem_out_ARREGION;
reg[0:0] m_axi_gmem_out_ARUSER;
reg m_axi_gmem_out_RREADY;
reg m_axi_gmem_out_BREADY;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_out_blk_n_AR;
reg    gmem_out_blk_n_AW;
wire    ap_CS_fsm_state8;
reg    gmem_out_blk_n_B;
wire    ap_CS_fsm_state15;
wire  signed [61:0] trunc_ln_fu_77_p4;
reg   [61:0] trunc_ln_reg_119;
wire  signed [61:0] trunc_ln138_1_fu_98_p4;
reg   [61:0] trunc_ln138_1_reg_129;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_start;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_done;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_idle;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_ready;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWVALID;
wire   [63:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWADDR;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWID;
wire   [31:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWLEN;
wire   [2:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWSIZE;
wire   [1:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWBURST;
wire   [1:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWLOCK;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWCACHE;
wire   [2:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWPROT;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWQOS;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWREGION;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWUSER;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WVALID;
wire   [31:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WDATA;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WSTRB;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WLAST;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WID;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WUSER;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARVALID;
wire   [63:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARADDR;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARID;
wire   [31:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARLEN;
wire   [2:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARSIZE;
wire   [1:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARBURST;
wire   [1:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARLOCK;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARCACHE;
wire   [2:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARPROT;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARQOS;
wire   [3:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARREGION;
wire   [0:0] grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARUSER;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_RREADY;
wire    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_BREADY;
reg    grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire  signed [63:0] sext_ln138_fu_87_p1;
wire  signed [63:0] sext_ln138_1_fu_108_p1;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_start_reg = 1'b0;
end

top_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3 grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_start),
    .ap_done(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_done),
    .ap_idle(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_idle),
    .ap_ready(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_ready),
    .m_axi_gmem_out_AWVALID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWVALID),
    .m_axi_gmem_out_AWREADY(m_axi_gmem_out_AWREADY),
    .m_axi_gmem_out_AWADDR(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWADDR),
    .m_axi_gmem_out_AWID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWID),
    .m_axi_gmem_out_AWLEN(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWLEN),
    .m_axi_gmem_out_AWSIZE(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWSIZE),
    .m_axi_gmem_out_AWBURST(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWBURST),
    .m_axi_gmem_out_AWLOCK(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWLOCK),
    .m_axi_gmem_out_AWCACHE(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWCACHE),
    .m_axi_gmem_out_AWPROT(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWPROT),
    .m_axi_gmem_out_AWQOS(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWQOS),
    .m_axi_gmem_out_AWREGION(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWREGION),
    .m_axi_gmem_out_AWUSER(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWUSER),
    .m_axi_gmem_out_WVALID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WVALID),
    .m_axi_gmem_out_WREADY(m_axi_gmem_out_WREADY),
    .m_axi_gmem_out_WDATA(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WDATA),
    .m_axi_gmem_out_WSTRB(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WSTRB),
    .m_axi_gmem_out_WLAST(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WLAST),
    .m_axi_gmem_out_WID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WID),
    .m_axi_gmem_out_WUSER(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WUSER),
    .m_axi_gmem_out_ARVALID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARVALID),
    .m_axi_gmem_out_ARREADY(m_axi_gmem_out_ARREADY),
    .m_axi_gmem_out_ARADDR(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARADDR),
    .m_axi_gmem_out_ARID(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARID),
    .m_axi_gmem_out_ARLEN(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARLEN),
    .m_axi_gmem_out_ARSIZE(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARSIZE),
    .m_axi_gmem_out_ARBURST(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARBURST),
    .m_axi_gmem_out_ARLOCK(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARLOCK),
    .m_axi_gmem_out_ARCACHE(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARCACHE),
    .m_axi_gmem_out_ARPROT(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARPROT),
    .m_axi_gmem_out_ARQOS(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARQOS),
    .m_axi_gmem_out_ARREGION(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARREGION),
    .m_axi_gmem_out_ARUSER(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARUSER),
    .m_axi_gmem_out_RVALID(m_axi_gmem_out_RVALID),
    .m_axi_gmem_out_RREADY(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_RREADY),
    .m_axi_gmem_out_RDATA(m_axi_gmem_out_RDATA),
    .m_axi_gmem_out_RLAST(m_axi_gmem_out_RLAST),
    .m_axi_gmem_out_RID(m_axi_gmem_out_RID),
    .m_axi_gmem_out_RFIFONUM(m_axi_gmem_out_RFIFONUM),
    .m_axi_gmem_out_RUSER(m_axi_gmem_out_RUSER),
    .m_axi_gmem_out_RRESP(m_axi_gmem_out_RRESP),
    .m_axi_gmem_out_BVALID(m_axi_gmem_out_BVALID),
    .m_axi_gmem_out_BREADY(grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_BREADY),
    .m_axi_gmem_out_BRESP(m_axi_gmem_out_BRESP),
    .m_axi_gmem_out_BID(m_axi_gmem_out_BID),
    .m_axi_gmem_out_BUSER(m_axi_gmem_out_BUSER),
    .sext_ln138_1(trunc_ln138_1_reg_129),
    .sext_ln138(trunc_ln_reg_119)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_start_reg <= 1'b1;
        end else if ((grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_ready == 1'b1)) begin
            grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        trunc_ln138_1_reg_129 <= {{output_r[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln_reg_119 <= {{input_r[63:2]}};
    end
end

always @ (*) begin
    if ((grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_out_BVALID == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_ARREADY == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_out_AWREADY == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((m_axi_gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        gmem_out_blk_n_AR = m_axi_gmem_out_ARREADY;
    end else begin
        gmem_out_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gmem_out_blk_n_AW = m_axi_gmem_out_AWREADY;
    end else begin
        gmem_out_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gmem_out_blk_n_B = m_axi_gmem_out_BVALID;
    end else begin
        gmem_out_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_out_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_out_ARADDR = sext_ln138_fu_87_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARADDR = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARADDR;
    end else begin
        m_axi_gmem_out_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARBURST = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARBURST;
    end else begin
        m_axi_gmem_out_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARCACHE = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARCACHE;
    end else begin
        m_axi_gmem_out_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARID;
    end else begin
        m_axi_gmem_out_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_out_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_out_ARLEN = 32'd400;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARLEN = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARLEN;
    end else begin
        m_axi_gmem_out_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARLOCK = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARLOCK;
    end else begin
        m_axi_gmem_out_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARPROT = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARPROT;
    end else begin
        m_axi_gmem_out_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARQOS = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARQOS;
    end else begin
        m_axi_gmem_out_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARREGION = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARREGION;
    end else begin
        m_axi_gmem_out_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARSIZE = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARSIZE;
    end else begin
        m_axi_gmem_out_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARUSER = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARUSER;
    end else begin
        m_axi_gmem_out_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_out_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_out_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_ARVALID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_ARVALID;
    end else begin
        m_axi_gmem_out_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem_out_AWADDR = sext_ln138_1_fu_108_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWADDR = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWADDR;
    end else begin
        m_axi_gmem_out_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWBURST = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWBURST;
    end else begin
        m_axi_gmem_out_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWCACHE = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWCACHE;
    end else begin
        m_axi_gmem_out_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWID;
    end else begin
        m_axi_gmem_out_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem_out_AWLEN = 32'd400;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWLEN = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWLEN;
    end else begin
        m_axi_gmem_out_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWLOCK = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWLOCK;
    end else begin
        m_axi_gmem_out_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWPROT = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWPROT;
    end else begin
        m_axi_gmem_out_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWQOS = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWQOS;
    end else begin
        m_axi_gmem_out_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWREGION = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWREGION;
    end else begin
        m_axi_gmem_out_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWSIZE = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWSIZE;
    end else begin
        m_axi_gmem_out_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWUSER = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWUSER;
    end else begin
        m_axi_gmem_out_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem_out_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_AWVALID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_AWVALID;
    end else begin
        m_axi_gmem_out_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        m_axi_gmem_out_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_BREADY = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_BREADY;
    end else begin
        m_axi_gmem_out_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_RREADY = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_RREADY;
    end else begin
        m_axi_gmem_out_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_out_WVALID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WVALID;
    end else begin
        m_axi_gmem_out_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_gmem_out_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((m_axi_gmem_out_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((m_axi_gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_start = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_ap_start_reg;

assign m_axi_gmem_out_WDATA = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WDATA;

assign m_axi_gmem_out_WID = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WID;

assign m_axi_gmem_out_WLAST = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WLAST;

assign m_axi_gmem_out_WSTRB = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WSTRB;

assign m_axi_gmem_out_WUSER = grp_f1_Pipeline_VITIS_LOOP_138_1_VITIS_LOOP_139_2_VITIS_LOOP_140_3_fu_69_m_axi_gmem_out_WUSER;

assign sext_ln138_1_fu_108_p1 = trunc_ln138_1_fu_98_p4;

assign sext_ln138_fu_87_p1 = trunc_ln_fu_77_p4;

assign trunc_ln138_1_fu_98_p4 = {{output_r[63:2]}};

assign trunc_ln_fu_77_p4 = {{input_r[63:2]}};

endmodule //top_f1
